name: pre-commit

on:
  pull_request:
  workflow_dispatch:

jobs:
  pre-commit:
    name: Pre-commit Linters
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
    - uses: pre-commit/action@v3.0.0
